// <auto-generated />
namespace API.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class InitialFieldconstr : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitialFieldconstr));
        
        string IMigrationMetadata.Id
        {
            get { return "201812181401366_Initial-Field constr"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
